import { MenuItem } from './types';

export const menuCategories = [
  { id: 'soyuq', titleAz: 'Soyuq Yeməklər', titleEn: 'Cold Appetizers', titleRu: 'Холодные Закуски' },
  { id: 'isti', titleAz: 'İsti Yeməklər', titleEn: 'Hot Dishes', titleRu: 'Горячие Блюда' },
  { id: 'tursu', titleAz: 'Turşular', titleEn: 'Pickles', titleRu: 'Соленья' },
  { id: 'ickiler', titleAz: 'İçkilər', titleEn: 'Drinks', titleRu: 'Напитки' },
  { id: 'desert', titleAz: 'Desert', titleEn: 'Desserts', titleRu: 'Десерты' },
  { id: 'hediyyeler', titleAz: 'Hədiyyələr', titleEn: 'Complimentary / Gifts', titleRu: 'Подарки и Шоу' }
] as const;

export const menuItems: MenuItem[] = [
  // SOYUQ YEMƏKLƏR (Cold Appetizers)
  {
    id: 's_tabaka',
    nameAz: 'Tabaka',
    nameEn: 'Cold Pressed Chicken Tabaka',
    nameRu: 'Цыпленок табака (холодный)',
    descriptionAz: 'Qızardılmış toyuq soyuq halda dilimlənmiş şəkildə təqdim olunur.',
    descriptionEn: 'Crispy fried chicken served chilled and sliced.',
    descriptionRu: 'Жареный цыпленок табака, нарезанный ломтиками и подаваемый холодным.',
    category: 'soyuq',
    price: 8,
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 's_qara_kuru',
    nameAz: 'Qara kürü',
    nameEn: 'Black Caviar',
    nameRu: 'Черная икра',
    descriptionAz: 'Yüksək keyfiyyətli qara kürü, kərıyağı ilə.',
    descriptionEn: 'High-quality black caviar served with fine butter.',
    descriptionRu: 'Высококачественная черная икра, подаваемая со сливочным маслом.',
    category: 'soyuq',
    price: 25,
    image: 'https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&q=80&w=600',
    tags: ['Premium', 'Gourmet']
  },
  {
    id: 's_qirmizi_kuru',
    nameAz: 'Qırmızı kürü',
    nameEn: 'Red Caviar',
    nameRu: 'Красная икра',
    descriptionAz: 'Təzə qırmızı qızılbalıq kürüsü, kərə yağı və tost ilə.',
    descriptionEn: 'Fresh red salmon caviar served with butter and toast.',
    descriptionRu: 'Свежая красная икра лосося с маслом и тостами.',
    category: 'soyuq',
    price: 30,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=600',
    tags: ['Classic']
  },
  {
    id: 's_soyutma_toyuq',
    nameAz: 'Soyutma toyuq',
    nameEn: 'Poached Chicken',
    nameRu: 'Отварная курица (Соютма)',
    descriptionAz: 'Təbii bulaq suyunda zərif bişirilmiş soyuq kənd toyuğu.',
    descriptionEn: 'Delicately poached country chicken, served cold with herbs.',
    descriptionRu: 'Нежно отваренная домашняя курица, подается холодной с зеленью.',
    category: 'soyuq',
    price: 12,
    image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 's_toyuq_tabaka',
    nameAz: 'Toyuq tabaka',
    nameEn: 'Chicken Tabaka Portion',
    nameRu: 'Курица табака (порция)',
    descriptionAz: 'Klassik basdırılmış qızardılmış çolpa.',
    descriptionEn: 'Classic pressed and fried baby chicken portion.',
    descriptionRu: 'Классический цыпленок табака, обжаренный под прессом.',
    category: 'soyuq',
    price: 10,
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 's_paytaxt_salati',
    nameAz: 'Paytaxt salatı',
    nameEn: 'Capital Olivier Salad',
    nameRu: 'Салат Столичный (Оливье)',
    descriptionAz: 'Seçilmiş tərəvəzlər, toyuq əti və ev mayonezi ilə klassik paytaxt salatı.',
    descriptionEn: 'Finely diced vegetables, chicken breast, and homemade mayonnaise green peas.',
    descriptionRu: 'Классический салат с отварными овощами, куриной грудкой и домашним майонезом.',
    category: 'soyuq',
    price: 6,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 's_mimoza',
    nameAz: 'Mimoza',
    nameEn: 'Mimosa Layered Salad',
    nameRu: 'Салат Мимоза',
    descriptionAz: 'Qat-qat düzülmüş toyuq, yumurta, yerkökü və holland pendiri.',
    descriptionEn: 'Traditional layered salad with shredded chicken, eggs, carrots, and cheese.',
    descriptionRu: 'Слоеный праздничный салат с курицей, тертыми яйцами, морковью и сыром.',
    category: 'soyuq',
    price: 7,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 's_suba',
    nameAz: 'Şuba',
    nameEn: 'Shuba Salad',
    nameRu: 'Сельдь под шубой',
    descriptionAz: 'Siyənək balığı filesi, çuğundur, kök və kartoflu klassik şuba.',
    descriptionEn: 'Classic herring under fur coat layered salad with beets and potatoes.',
    descriptionRu: 'Традиционный слоеный салат с сельдью, свеклой, картофелем и майонезом.',
    category: 'soyuq',
    price: 8,
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 's_blincik_et',
    nameAz: 'Blinçik (ət)',
    nameEn: 'Meat Crepes',
    nameRu: 'Блинчики с мясом',
    descriptionAz: 'Təzə dana qiyməsi ilə doldurulmuş ev blinçikləri.',
    descriptionEn: 'Thin homemade crepes folded with seasoned minced beef.',
    descriptionRu: 'Тонкие домашние блинчики с начинкой из обжаренного говяжьего фарша.',
    category: 'soyuq',
    price: 8,
    image: 'https://images.unsplash.com/photo-1621961404018-81990fec2bc9?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 's_blincik_kesmik',
    nameAz: 'Blinçik (kəsmik)',
    nameEn: 'Cottage Cheese Crepes',
    nameRu: 'Блинчики с творогом',
    descriptionAz: 'Zərif şirin kəsmik ilə bükülmüş ev blinçikləri.',
    descriptionEn: 'Light crepes folded with sweet cottage cheese filling.',
    descriptionRu: 'Нежные блинчики со сладкой творожной начинкой.',
    category: 'soyuq',
    price: 6,
    image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 's_pendir_holland',
    nameAz: 'Pendir (Holland)',
    nameEn: 'Dutch Cheese Platter',
    nameRu: 'Сыр Голландский',
    descriptionAz: 'Dilimlənmiş qaymaqlı holland pendiri assortisi.',
    descriptionEn: 'Fine slices of premium hard cheese.',
    descriptionRu: 'Нарезка качественного полутвердого голландского сыра.',
    category: 'soyuq',
    price: 10,
    image: 'https://images.unsplash.com/photo-1486299267070-83823f5448dd?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 's_pendir_ismayilli',
    nameAz: 'Pendir (İsmayıllı)',
    nameEn: 'Ismayilli Sheep Cheese',
    nameRu: 'Сыр Исмаиллинский',
    descriptionAz: 'İsmayıllı dağlarında hazırlanan ənənəvi şor qoyun pendiri.',
    descriptionEn: 'Traditional salty mountain sheep cheese from the Ismayilli region.',
    descriptionRu: 'Натуральный соленый овечий сыр из экологически чистого Исмаиллы.',
    category: 'soyuq',
    price: 8,
    image: 'https://images.unsplash.com/photo-1552767059-ce182ead6c1b?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 's_pendir_sacaq',
    nameAz: 'Pendir (Saçaq)',
    nameEn: 'Braided String Cheese',
    nameRu: 'Сыр Чечил (Косичка)',
    descriptionAz: 'Duza qoyulmuş klassik milli saçaq pendiri.',
    descriptionEn: 'Tangled and lightly salted national braided string cheese.',
    descriptionRu: 'Волокнистый соленый сыр косичка домашнего приготовления.',
    category: 'soyuq',
    price: 8,
    image: 'https://images.unsplash.com/photo-1528256864284-4710d2388496?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 's_kolbasa_servalat',
    nameAz: 'Kolbasa (Servalat)',
    nameEn: 'Cervelat Salami Slices',
    nameRu: 'Колбаса Сервелат',
    descriptionAz: 'Hisə verilmiş premium keyfiyyətli servalat assortisi.',
    descriptionEn: 'Premium grade wood-smoked cervelat salami cold cuts.',
    descriptionRu: 'Ароматная нарезка копченого сервелата высшего сорта.',
    category: 'soyuq',
    price: 9,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 's_kolbasa_ovcu',
    nameAz: 'Kolbasa (Ovçu)',
    nameEn: 'Huntsman Smoked Sausage',
    nameRu: 'Колбаса Охотничья',
    descriptionAz: 'Xırda ədviyyatlı hisə verilmiş ovçu kolbasaları.',
    descriptionEn: 'Spicy traditional hot-smoked huntsman sausages.',
    descriptionRu: 'Копченые пикантные охотничьи колбаски.',
    category: 'soyuq',
    price: 9,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 's_kolbasa_oxodnik',
    nameAz: 'Kolbasa (Oxodnik)',
    nameEn: 'Okhotnik Gourmet Sausage',
    nameRu: 'Колбаса Охотник',
    descriptionAz: 'Xüsusi ətirli və ədviyyatlı quru-hisə verilmiş kolbasa.',
    descriptionEn: 'Garlic-infused cured Okhotnik dry sausage slices.',
    descriptionRu: 'Сухокопченая пряная чесночная колбаса.',
    category: 'soyuq',
    price: 9,
    image: 'https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 's_xiyar_teze',
    nameAz: 'Xiyar (təzə)',
    nameEn: 'Fresh Cucumbers',
    nameRu: 'Свежие огурцы',
    descriptionAz: 'Binə bağlarından təzə yığılmış xırtıldayan xiyarlar.',
    descriptionEn: 'Fresh, crunchy organic cucumbers from domestic gardens.',
    descriptionRu: 'Свежие хрустящие огурцы из местных теплиц поселка Бина.',
    category: 'soyuq',
    price: 4,
    image: 'https://images.unsplash.com/photo-1449339091482-36d2461be771?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 's_pomidor_teze',
    nameAz: 'Pomidor (təzə)',
    nameEn: 'Fresh Tomatoes',
    nameRu: 'Свежие помидоры',
    descriptionAz: 'Şirinliyi ilə tanınan Binə pomidorları.',
    descriptionEn: 'Famous sweet and juicy tomatoes from Baku glasshouses.',
    descriptionRu: 'Сочные, ароматные бакинские томаты.',
    category: 'soyuq',
    price: 5,
    image: 'https://images.unsplash.com/photo-1595855759920-86582396756a?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 's_goyerti_cesid',
    nameAz: 'Göyərti (çeşid)',
    nameEn: 'Assorted Fresh Herbs',
    nameRu: 'Ассорти свежей зелени',
    descriptionAz: 'Reyhan, keşniş, şüyüd, göy soğan və tərxun qarışığı.',
    descriptionEn: 'A healthy selection of fresh regional coriander, dill, and wild tarragon.',
    descriptionRu: 'Тарелка свежей зелени: рейхан, кинза, укроп, зеленый лук.',
    category: 'soyuq',
    price: 5,
    image: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb19675?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 's_isgenderiyye',
    nameAz: 'İsgəndəriyyə',
    nameEn: 'Alexandria Roasted Beef Salad',
    nameRu: 'Салат Александрия',
    descriptionAz: 'Təzə qaynadılmış qırmızı ət dilimləri və şirin bibər assortisi.',
    descriptionEn: 'Slow-cooked beef strips tossed with fresh sweet bell peppers and light dressing.',
    descriptionRu: 'Салат с нежными ломтиками отварной говядины и болгарским перцем.',
    category: 'soyuq',
    price: 8,
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 's_suzme',
    nameAz: 'Süzmə',
    nameEn: 'Strained Herb Yogurt',
    nameRu: 'Сюзме',
    descriptionAz: 'Qatı milli süzmə, sarımsaq və quru nanə ilə bəzədilmiş.',
    descriptionEn: 'Thick strained traditional homemade yogurt with garlic, dried mint, and olive oil.',
    descriptionRu: 'Густой процеженный национальный йогурт с мятой и чесноком.',
    category: 'soyuq',
    price: 5,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 's_acixsa',
    nameAz: 'Acıxsa',
    nameEn: 'Adjika Sauce',
    nameRu: 'Аджика',
    descriptionAz: 'Qırmızı acı bibər, sarımsaq və ləzzətli ədviyyatlar püresi.',
    descriptionEn: 'Spicy homemade red chili paste infused with garlic and local Caucasian spices.',
    descriptionRu: 'Острая красная аджика домашнего приготовления.',
    category: 'soyuq',
    price: 4,
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 's_limon_dogranmis',
    nameAz: 'Limon (doğranmış)',
    nameEn: 'Sliced Lemon Platter',
    nameRu: 'Лимон (нарезка)',
    descriptionAz: 'Təzə dilimlənmiş şirəli limon boşqabı.',
    descriptionEn: 'Vibrant slices of organic lemons, perfect with cold caviar.',
    descriptionRu: 'Нарезка сочного свежего лимона.',
    category: 'soyuq',
    price: 3,
    image: 'https://images.unsplash.com/photo-1534080391025-a134628f2510?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 's_corek_ag',
    nameAz: 'Çörək (ağ)',
    nameEn: 'White Bread',
    nameRu: 'Хлеб белый',
    descriptionAz: 'Təndirdə və ya gildə bişmiş ətirli təzə ağ çörək.',
    descriptionEn: 'Hearth-baked fresh white bread, soft inside.',
    descriptionRu: 'Ароматный белый домашний хлеб.',
    category: 'soyuq',
    price: 2,
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 's_corek_qara',
    nameAz: 'Çörək (qara)',
    nameEn: 'Black Rye Bread',
    nameRu: 'Хлеб черный',
    descriptionAz: 'Xüsusi taxıllı klassik çovdar qara çörəyi.',
    descriptionEn: 'Traditional dark sourdough rye bread.',
    descriptionRu: 'Полезный ржаной черный хлеб.',
    category: 'soyuq',
    price: 2,
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 's_yag',
    nameAz: 'Yağ',
    nameEn: 'Butter portion',
    nameRu: 'Масло сливочное',
    descriptionAz: 'Yeməklər və kürü ilə ideal kərə yağı porsiyası.',
    descriptionEn: 'Pure, rich local table butter roll.',
    descriptionRu: 'Натуральное сливочное масло к чаю или икре.',
    category: 'soyuq',
    price: 2,
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 's_narserab',
    nameAz: 'Nar şərab',
    nameEn: 'Narsharab Sauce',
    nameRu: 'Наршараб',
    descriptionAz: 'Ölkəmizin təbii narlarından hazırlanan turş-şirin xüsusi sous.',
    descriptionEn: 'Classic sweet-tart pomegranate reduction glaze.',
    descriptionRu: 'Гранатовый соус к рыбе и шашлыку.',
    category: 'soyuq',
    price: 6,
    image: 'https://images.unsplash.com/photo-1511113593219-c02118e7751c?auto=format&fit=crop&q=80&w=600'
  },

  // İSTİ YEMƏKLƏR (Hot Dishes)
  {
    id: 'i_qutab_et',
    nameAz: 'Qutab (ət)',
    nameEn: 'Meat Qutab',
    nameRu: 'Кутаб с мясом',
    descriptionAz: 'Nazik xəmirdə ədviyyatlı quzu qiyməsi ilə doldurulmuş sac qutabı.',
    descriptionEn: 'Flatbread stuffed with spiced minced meat, grilled on dynamic convex iron saj.',
    descriptionRu: 'Тонкий пирожок с мясным фаршем, обжаренный на сухом садже.',
    category: 'isti',
    price: 4,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'i_qutab_goy',
    nameAz: 'Qutab (göy)',
    nameEn: 'Herb Qutab',
    nameRu: 'Кутаб с зеленью',
    descriptionAz: 'Təzə dağ göyərtiləri ilə doldurulmuş sac qutabı.',
    descriptionEn: 'Thin griddled flatbread packed with chopped wild greens.',
    descriptionRu: 'Кутаб со свежей сезонной зеленью.',
    category: 'isti',
    price: 3,
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'i_buglama',
    nameAz: 'Buğlama (qovurma)',
    nameEn: 'Bughlama (Stewed Lamb)',
    nameRu: 'Буглама (тушеная ягнятина)',
    descriptionAz: 'Pomidor, bibər və zəfəran buğunda zərif bişirilmiş quzu qovurması.',
    descriptionEn: 'Rich, slow-braised lamb stewed in its juices with sweet peppers & tomatoes.',
    descriptionRu: 'Томленая ягнятина в собственном соку со сладким перцем, томатами и базиликом.',
    category: 'isti',
    price: 18,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600',
    tags: ['Traditional']
  },
  {
    id: 'i_sac_icali',
    nameAz: 'Sac (içəli)',
    nameEn: 'Saj Meat Medley',
    nameRu: 'Садж мясной с потрохами',
    descriptionAz: 'Quzu içalatı ilə tərəvəzlərin sac tavasında qızardılmış lüks təqdimatı.',
    descriptionEn: 'Sizzling cast-iron pan loaded with lamb offal and crisp country potatoes.',
    descriptionRu: 'Шипящее марочное блюдо на садже с ливером и хрустящим картофелем.',
    category: 'isti',
    price: 22,
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'i_tika_kabab',
    nameAz: 'Tikə kabab',
    nameEn: 'Tika Shish Kebab',
    nameRu: 'Тике кабаб (шашлык из ягненка)',
    descriptionAz: 'Manqalda, köz alovunda bişirilmiş quzu tikələri.',
    descriptionEn: 'Skewered wood-charred lamb fillets with light sumac dust.',
    descriptionRu: 'Сочные куски филе ягненка, зажаренные на дровах на шомполах.',
    category: 'isti',
    price: 16,
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?auto=format&fit=crop&q=80&w=600',
    tags: ['Coals']
  },
  {
    id: 'i_lule_kabab',
    nameAz: 'Lülə kabab',
    nameEn: 'Lula minced Kebab',
    nameRu: 'Люля кабаб',
    descriptionAz: 'Zərif çəkilmiş quzu quyruq ətindən hazırlanmış şirəli lülə kababı.',
    descriptionEn: 'Perfectly skewered minced lamb blended with tail fat and onion.',
    descriptionRu: 'Нежнейший фарш из баранины с курдюком, приготовленный на углях.',
    category: 'isti',
    price: 14,
    image: 'https://images.unsplash.com/photo-1514516345957-556ca7d90a29?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'i_toyuq_kabab',
    nameAz: 'Toyuq kabab',
    nameEn: 'Chicken Kebab',
    nameRu: 'Шашлык из курицы',
    descriptionAz: 'Zəfəran marinar və soğan suyu ilə manqalda qızarmış şirəli çolpa bədəni.',
    descriptionEn: 'Luminous saffron-marinated bone-in chicken thighs grilled over pit.',
    descriptionRu: 'Куриный шашлык в шафрановом маринаде.',
    category: 'isti',
    price: 12,
    image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'i_bildircin_kabab',
    nameAz: 'Bildirçin kabab',
    nameEn: 'Quail Kebab',
    nameRu: 'Шашлык из перепелки',
    descriptionAz: 'Közdə bişilən zərif bütöv bildirçin quşları.',
    descriptionEn: 'Young local quails flame-grilled and glazed lightly with butter.',
    descriptionRu: 'Нежные тушки перепелок, обжаренные на углях.',
    category: 'isti',
    price: 15,
    image: 'https://images.unsplash.com/photo-1546964124-0cce460f38ef?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'i_ciger_kabab',
    nameAz: 'Ciyər kababı',
    nameEn: 'Liver Kebab',
    nameRu: 'Шашлык из печени',
    descriptionAz: 'Quzu ciyərinin quyruq yağları ilə kömürdə bütöv şiş bişirilməsi.',
    descriptionEn: 'Delicious lamb liver cubes skewered with tail-fat for extreme moisture.',
    descriptionRu: 'Шашлык из бараньей печени с кусочками хрустящего курдюка.',
    category: 'isti',
    price: 12,
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'i_dana_basdirmasi',
    nameAz: 'Dana basdırması',
    nameEn: 'Beef Basturma Kebab',
    nameRu: 'Бастурма из говядины (шашлык)',
    descriptionAz: 'Kəklikotu və ədviyyatlarla zərifləşdirilmiş dana əti şişi.',
    descriptionEn: 'Premium chunks of beef loin marinated with mountain thyme and red pepper.',
    descriptionRu: 'Нежные куски говяжьей вырезки, маринованные с чабрецом.',
    category: 'isti',
    price: 20,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600',
    tags: ['Gourmet']
  },
  {
    id: 'i_plov',
    nameAz: 'Plov (qara ilə)',
    nameEn: 'Royal Plov with lamb',
    nameRu: 'Плов с бараниной (кара)',
    descriptionAz: 'Süzmə zəfəranlı uzun düyü, şabalıd, ərik, üzüm və dana/quzu qovurması ilə.',
    descriptionEn: 'Steamed basmati rice with dried apricots, chestnuts, and braised lamb shank.',
    descriptionRu: 'Праздничный плов с каштанами, сухофруктами и томленой ягнятиной.',
    category: 'isti',
    price: 12,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&q=80&w=600',
    tags: ['Special']
  },
  {
    id: 'i_baliq',
    nameAz: 'Balıq',
    nameEn: 'Fried / Grilled Fish',
    nameRu: 'Рыба на углях',
    descriptionAz: 'Xəzər dənizindən təzə gətirilmiş balıq qızartması.',
    descriptionEn: 'Freshly caught Caspian fish, seasoned and pan-seared or grilled.',
    descriptionRu: 'Свежая каспийская рыба, обжаренная до золотистой корочки.',
    category: 'isti',
    price: 18,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&q=80&w=600'
  },

  // TURŞULAR (Pickles)
  {
    id: 't_zeytun_yasil',
    nameAz: 'Zeytun (yaşıl)',
    nameEn: 'Green Olives',
    nameRu: 'Оливки зеленые',
    descriptionAz: 'Ev üsulu duzlu böyük yaşıl zeytun boşqabı.',
    descriptionEn: 'Large local green olives cured with lemon spears.',
    descriptionRu: 'Крупные отборные зеленые оливки домашнего посола.',
    category: 'tursu',
    price: 5,
    image: 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 't_xiyar_yasil',
    nameAz: 'Xiyar (yaşıl)',
    nameEn: 'Green Pickled Gherkins',
    nameRu: 'Соленые огурцы (зеленые)',
    descriptionAz: 'Çəlləkdə xüsusi ədviyyatlarla qoyulmuş yaşıl xiyar şorabası.',
    descriptionEn: 'Traditional barrel-cured green cucumbers.',
    descriptionRu: 'Бочковые зеленые соленые огурчики.',
    category: 'tursu',
    price: 4,
    image: 'https://images.unsplash.com/photo-1589135799158-f54f76269661?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 't_xiyar_ag',
    nameAz: 'Xiyar (ağ)',
    nameEn: 'White Pickled Cucumbers',
    nameRu: 'Соленые огурцы (белые)',
    descriptionAz: 'Üzüm sirkəsində turşuya qoyulmuş xırda ağ xiyarlar.',
    descriptionEn: 'Lightly brined crispy white cucumbers.',
    descriptionRu: 'Хрустящие белые огурцы в винном уксусе.',
    category: 'tursu',
    price: 4,
    image: 'https://images.unsplash.com/photo-1589135799158-f54f76269661?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 't_alca',
    nameAz: 'Alça',
    nameEn: 'Pickled Green Plums',
    nameRu: 'Соленая алыча',
    descriptionAz: 'Turş-şirin dənəli təbii bahar alçası şorabası.',
    descriptionEn: 'Tart brine-cured spring green cherry plums.',
    descriptionRu: 'Алыча весеннего сбора в фирменном рассоле.',
    category: 'tursu',
    price: 5,
    image: 'https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 't_qarisig',
    nameAz: 'Qarışıq',
    nameEn: 'Grand Mixed Pickle Board',
    nameRu: 'Ассорти солений',
    descriptionAz: 'Ev üsulu hazırlanmış çeşidli tərəvəz turşuları.',
    descriptionEn: 'Platter of pickled cauliflower, carrots, and sweet peppers.',
    descriptionRu: 'Домашнее ассорти из цветной капусты, моркови и перцев.',
    category: 'tursu',
    price: 6,
    image: 'https://images.unsplash.com/photo-1589135799158-f54f76269661?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 't_pomidor',
    nameAz: 'Pomidor',
    nameEn: 'Pickled Tomatoes',
    nameRu: 'Соленые томаты',
    descriptionAz: 'Sarımsaq və tərxun ilə marinada qoyulmuş pomidorlar.',
    descriptionEn: 'Aromatic pickled tomatoes packed with celery roots.',
    descriptionRu: 'Ароматные квашеные помидоры с чесноком и сельдереем.',
    category: 'tursu',
    price: 5,
    image: 'https://images.unsplash.com/photo-1595855759920-86582396756a?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 't_armud',
    nameAz: 'Armud',
    nameEn: 'Pickled Pears',
    nameRu: 'Маринованная груша',
    descriptionAz: 'Zərif mixəkli sirkədə bişmiş bütöv yabanı armud şorabası.',
    descriptionEn: 'Fragrant wild mountain pears pickled with dynamic clove.',
    descriptionRu: 'Дикая лесная груша маринованная с корицей и гвоздикой.',
    category: 'tursu',
    price: 5,
    image: 'https://images.unsplash.com/photo-1514733670139-4d87a19bc177?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 't_ozgul',
    nameAz: 'Özgül / Əzgil',
    nameEn: 'Pickled Wild Medlars',
    nameRu: 'Соленая мушмула',
    descriptionAz: 'Meşə əzgilinin turşməzə ənənəvi süfrə şorabası.',
    descriptionEn: 'Wild medlar forest fruits gathered and brine-aged.',
    descriptionRu: 'Кисло-сладкая лесная мушмула в собственном соку.',
    category: 'tursu',
    price: 4,
    image: 'https://images.unsplash.com/photo-1514733670139-4d87a19bc177?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 't_zogal',
    nameAz: 'Zoğal',
    nameEn: 'Pickled Cornelian Cherries',
    nameRu: 'Соленый кизил',
    descriptionAz: 'Ölkəmizin zərif meşə zoğallarından duzlu şoraba.',
    descriptionEn: 'Bright red mountain cornelian cherries brine-cured.',
    descriptionRu: 'Кизил лесного сбора в соленом маринаде.',
    category: 'tursu',
    price: 5,
    image: 'https://images.unsplash.com/photo-1511113593219-c02118e7751c?auto=format&fit=crop&q=80&w=600'
  },

  // İÇKİLƏR (Drinks)
  {
    id: 'd_sire_albali',
    nameAz: 'Təbii Şirə - Albalı',
    nameEn: 'Cherry Juice',
    nameRu: 'Натуральный сок - Вишня',
    descriptionAz: 'Albalı meyvələrindən hazırlanmış 100% natural soyuq şirə.',
    descriptionEn: '100% natural organic cherry nectar.',
    descriptionRu: 'Натуральный вишневый сок холодного отжима.',
    category: 'ickiler',
    price: 5,
    image: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'd_sire_saftali',
    nameAz: 'Təbii Şirə - Şaftalı',
    nameEn: 'Peach Juice',
    nameRu: 'Натуральный сок - Персик',
    descriptionAz: 'Qatı ətirli vitaminli şeftəli təbii nektarı.',
    descriptionEn: 'Rich sweet peach nectar.',
    descriptionRu: 'Персиковый сок с мякотью.',
    category: 'ickiler',
    price: 5,
    image: 'https://images.unsplash.com/photo-1603569283847-be40662c0c91?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'd_sire_moruq',
    nameAz: 'Təbii Şirə - Moruq',
    nameEn: 'Raspberry Elixir',
    nameRu: 'Натуральный сок - Малина',
    descriptionAz: 'Göyərtili meşə moruqlarından şirə.',
    descriptionEn: 'Delicious wild sweet red raspberry juice.',
    descriptionRu: 'Сок из свежей лесной малины.',
    category: 'ickiler',
    price: 5,
    image: 'https://images.unsplash.com/photo-1571115177098-24ec42ed635d?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'd_limonad_duses',
    nameAz: 'Limonad - Düşes',
    nameEn: 'Duchess Pear Lemonade',
    nameRu: 'Лимонад Дюшес',
    descriptionAz: 'Milli şüşə qablaşdırmada canlandırıcı armud ətirli qazlı içki.',
    descriptionEn: 'The iconic Azerbaijani sweet fizzy pear lemonade.',
    descriptionRu: 'Традиционный сильногазированный грушевый лимонад Дюшес.',
    category: 'ickiler',
    price: 4,
    image: 'https://images.unsplash.com/photo-1543258103-a62bdc069871?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'd_limonad_terxun',
    nameAz: 'Limonad - Tərxun',
    nameEn: 'Tarragon Green Lemonade',
    nameRu: 'Лимонад Тархун',
    descriptionAz: 'Tərxun bitkisi əsasında parlaq yaşıl ətirli şirin limonad.',
    descriptionEn: 'Herbal sweet tarragon green lemonade.',
    descriptionRu: 'Душистый советский изумрудный лимонад на экстракте тархуна.',
    category: 'ickiler',
    price: 4,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'd_qazli_su',
    nameAz: 'Qazlı su',
    nameEn: 'Sparkling Water',
    nameRu: 'Минеральная вода газированная',
    descriptionAz: 'Badamlı və ya Sirab bulaqlarının soyuq premium qazlı mineral suyu.',
    descriptionEn: 'Ice cold carbonated natural spring mineral water.',
    descriptionRu: 'Освежающая газированная минеральная вода Бадамлы или Сираб.',
    category: 'ickiler',
    price: 2,
    image: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'd_qazsiz_su',
    nameAz: 'Qazsız su',
    nameEn: 'Still Mineral Water',
    nameRu: 'Минеральная вода без газа',
    descriptionAz: 'Saf dondurulmuş büllur qazsız süfrə suyu.',
    descriptionEn: 'Pure and pristine local flat spring water.',
    descriptionRu: 'Охлажденная столовая чистая родниковая вода.',
    category: 'ickiler',
    price: 2,
    image: 'https://images.unsplash.com/photo-1616118132261-ec64db8964ac?auto=format&fit=crop&q=80&w=600'
  },

  // DESERT (Desserts)
  {
    id: 'de_qoz_lopesi',
    nameAz: 'Qoz löpəsi',
    nameEn: 'Walnut Kernels',
    nameRu: 'Очищенный грецкий орех',
    descriptionAz: 'Ağ rəngli ləzzətli təmizlənmiş Ordubad qozu.',
    descriptionEn: 'Premium sweet white walnut halves from regional organic trees.',
    descriptionRu: 'Отборные половинки светлого очищенного грецкого ореха.',
    category: 'desert',
    price: 6,
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'de_findiq_lopesi',
    nameAz: 'Fındıq löpəsi',
    nameEn: 'Hazelnut Kernels',
    nameRu: 'Ядра фундука',
    descriptionAz: 'Zaqatala meşələrindən toplanmış və azca qovrulmuş fındıqlar.',
    descriptionEn: 'Toasted crisp golden hazelnuts from regional groves.',
    descriptionRu: 'Натуральный слегка обжаренный лесной фундук из Закатал.',
    category: 'desert',
    price: 6,
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'de_araxis',
    nameAz: 'Araxis',
    nameEn: 'Salted Roasted Peanuts',
    nameRu: 'Арахис',
    descriptionAz: 'Duz ilə qovrulmuş təmizlənmiş ləvazimat.',
    descriptionEn: 'Gently roasted and salted peanuts.',
    descriptionRu: 'Обжаренный соленый золотистый арахис.',
    category: 'desert',
    price: 5,
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'de_cay_limonlu',
    nameAz: 'Çay (limonla)',
    nameEn: 'Samovar Tea with Lemon',
    nameRu: 'Чай с лимоном',
    descriptionAz: 'Lənkəran dağlarından bədii dəm, təzə limon dilimləri ilə.',
    descriptionEn: 'Fragrant premium Azerbaijani black tea, served in armudu with lemon.',
    descriptionRu: 'Свежезаваренный азербайджанский чай в армуды, с лимоном.',
    category: 'desert',
    price: 3,
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'de_kofe',
    nameAz: 'Kofe',
    nameEn: 'Artisanal Coffee',
    nameRu: 'Кофе',
    descriptionAz: 'Zəngin ətirli təzə çəkilmiş Espresso və ya Americano qəhvəsi.',
    descriptionEn: 'Rich, finely brewed traditional Espresso or Americano.',
    descriptionRu: 'Классический эспрессо или американо из арабики.',
    category: 'desert',
    price: 4,
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'de_sokolad',
    nameAz: 'Şokolad',
    nameEn: 'Premium Chocolates',
    nameRu: 'Шоколадное ассорти',
    descriptionAz: 'Nəfis şokolad plitələri dillimləri.',
    descriptionEn: 'Fine selection of imported Belgian chocolates.',
    descriptionRu: 'Бельгийские конфеты и дольки горького шоколада.',
    category: 'desert',
    price: 5,
    image: 'https://images.unsplash.com/photo-1511381939415-e44015466834?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'de_kismis',
    nameAz: 'Kişmiş',
    nameEn: 'Dry Raisins',
    nameRu: 'Изюм',
    descriptionAz: 'Abşeron üzümlərindən təbii dənəvər kişmiş.',
    descriptionEn: 'Sweet sun-dried yellow and dark golden raisins.',
    descriptionRu: 'Отборный светлый изюм к чаю.',
    category: 'desert',
    price: 4,
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'de_dondurma',
    nameAz: 'Dondurma (mövsümi)',
    nameEn: 'Seasonal Ice Cream',
    nameRu: 'Мороженое (сезонное)',
    descriptionAz: 'Ev üsulu şirin dondurma topları, şokolad sousu ilə.',
    descriptionEn: 'House-made vanilla, chocolate and berry ice cream scoops.',
    descriptionRu: 'Нежный домашний пломбир, украшенный орешками и топпингом.',
    category: 'desert',
    price: 6,
    image: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'de_meyve',
    nameAz: 'Meyvə (mövsümi)',
    nameEn: 'Seasonal Fruit Platter',
    nameRu: 'Фруктовая тарелка (сезонная)',
    descriptionAz: 'Seçilmiş Abşeron inciri, Quba alması, Göyçay narı assortisi.',
    descriptionEn: 'Abundant slice of fresh local summer and autumn fruits.',
    descriptionRu: 'Свежие сезонные фрукты: инжир, яблоки, гранат и слива.',
    category: 'desert',
    price: 8,
    image: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?auto=format&fit=crop&q=80&w=600'
  },

  // HƏDİYYƏLƏR / COMPLIMENTARY (Hədiyyələr)
  {
    id: 'h_tort',
    nameAz: 'Tort',
    nameEn: 'Celebration Birthday Cake',
    nameRu: 'Праздничный торт',
    descriptionAz: 'Doğum günü sahibləri üçün Vega Hall-dan şirin hədiyyə!',
    descriptionEn: 'Complimentary birthday cake design gifted generously by Vega Hall!',
    descriptionRu: 'Подарочный именинный торт от заведения для гостей Vega Hall!',
    category: 'hediyyeler',
    price: 0,
    image: 'https://images.unsplash.com/photo-1535141192574-5d4897c13636?auto=format&fit=crop&q=80&w=600',
    tags: ['Birthday Only', 'Free']
  },
  {
    id: 'h_ates_fesanliq',
    nameAz: 'Atəş-fəşanlıq',
    nameEn: 'Outdoor Fireworks Display',
    nameRu: 'Праздничный салют',
    descriptionAz: 'Böyük banketlərdə axşama heyranedici atəş-fəşanlıq şousu.',
    descriptionEn: 'Stunning outdoor fireworks display arranged at our event garden.',
    descriptionRu: 'Грандиозный вечерний салют на открытой территории ресторана.',
    category: 'hediyyeler',
    price: 0,
    image: 'https://images.unsplash.com/photo-1531685250784-7569952593d2?auto=format&fit=crop&q=80&w=600',
    tags: ['Free']
  },
  {
    id: 'h_serab_masasi',
    nameAz: 'Şərab masası',
    nameEn: 'Elite Wine Welcome Station',
    nameRu: 'Приветственный винный стол',
    descriptionAz: 'Qonaqların qarşılanması üçün təntənəli şərab süfrəsi.',
    descriptionEn: 'Decorative self-serve wine station for welcoming active guests.',
    descriptionRu: 'Элегантный фуршетный стол с местными винами для встречи гостей.',
    category: 'hediyyeler',
    price: 0,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=600',
    tags: ['Free']
  },
  {
    id: 'h_firsat_masasi',
    nameAz: 'Fürsət masası',
    nameEn: 'Occasion Opportunity Table',
    nameRu: 'Стол возможностей и сюрпризов',
    descriptionAz: 'Qapıda təşkil edilən xüsusi qeyd və xatirə guşəsi.',
    descriptionEn: 'Interactive memory photo and accessory stand for visitors.',
    descriptionRu: 'Декорированный интерактивный стенд для пожеланий.',
    category: 'hediyyeler',
    price: 0,
    image: 'https://images.unsplash.com/photo-1530101121876-80bc850e7ab5?auto=format&fit=crop&q=80&w=600',
    tags: ['Free']
  },
  {
    id: 'h_bay_gulu',
    nameAz: 'Bay-gülün masası',
    nameEn: 'Floristry Backdrop Stage',
    nameRu: 'Резиденция Бая-Цветочника',
    descriptionAz: 'Təbii güllərdən və asma fənərlərdən təşkil olunmuş möhtəşəm fotozona taxtı.',
    descriptionEn: 'High-end floral installations and romantic backlight photo canvas.',
    descriptionRu: 'Величественная фотозона, украшенная живыми цветами и огнями.',
    category: 'hediyyeler',
    price: 0,
    image: 'https://images.unsplash.com/photo-1545232979-8bf34eb9757b?auto=format&fit=crop&q=80&w=600',
    tags: ['Free']
  },
  {
    id: 'h_pul_qutu',
    nameAz: 'Pul yazan qutu',
    nameEn: 'Gift Envelope Chest',
    nameRu: 'Сундук для открыток и подарков',
    descriptionAz: 'Elegant qızılı naxışlı məbəd stilində sandıq xidməti.',
    descriptionEn: 'Secure dynamic lock velvet chest for attendee envelope letters.',
    descriptionRu: 'Сейф-сундук в винтажном стиле для подарочных конвертов.',
    category: 'hediyyeler',
    price: 0,
    image: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=600',
    tags: ['Free']
  },
  {
    id: 'h_trio_gelin',
    nameAz: 'Trio gəlin gətirmə',
    nameEn: 'Virtuoso Arrival Violin Trio',
    nameRu: 'Свадебное инструментальное трио',
    descriptionAz: 'Mərasimə gələn bəy və gəlin üçün canlı orkestr üçlüyünün çıxışı.',
    descriptionEn: 'Three classically dressed live musicians playing on entrance walks.',
    descriptionRu: 'Живое выступление инструментального трио при встрече молодых.',
    category: 'hediyyeler',
    price: 0,
    image: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&q=80&w=600',
    tags: ['Free']
  },
  {
    id: 'h_devetname',
    nameAz: 'Dəvətnamə',
    nameEn: 'Digital RSVP Invitations',
    nameRu: 'Пригласительные открытки (RSVP)',
    descriptionAz: 'Sizin adınıza xüsusi dizayn edilmiş rəqəmsal dəvətnamələrin hazırlanması.',
    descriptionEn: 'Elegant bespoke invitations custom built for your guests.',
    descriptionRu: 'Создание стильных дизайнерских приглашений для гостей.',
    category: 'hediyyeler',
    price: 0,
    image: 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&q=80&w=600',
    tags: ['Free']
  },
  {
    id: 'h_reqs_proqrami',
    nameAz: 'Rəqs proqramı',
    nameEn: 'Artisanal Orchestrated Dance Show',
    nameRu: 'Танцевальное шоу',
    descriptionAz: 'Gecə boyunca peşəkar milli rəqs ansamblının möhtəşəm çıxışları.',
    descriptionEn: 'Professional cultural dances performed by costumed dancers.',
    descriptionRu: 'Выступления профессионального танцевального ансамбля в костюмах.',
    category: 'hediyyeler',
    price: 0,
    image: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&q=80&w=600',
    tags: ['Free']
  },
  {
    id: 'h_pulsuz_bar',
    nameAz: 'Pulsuz bar xidməti',
    nameEn: 'Complimentary Open Bar Set',
    nameRu: 'Бесплатный открытый бар',
    descriptionAz: 'Qeyd olunan böyük qruplara lüks içkilər və kokteyllər servis tərəfimizdən təmin olunur.',
    descriptionEn: 'An open mocktail and beverages mixing bar serviced during the feast.',
    descriptionRu: 'Обслуживание гостей за барной стойкой во время всего торжества.',
    category: 'hediyyeler',
    price: 0,
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&q=80&w=600',
    tags: ['Free']
  }
];
